### PR TITLE
Pokemon + Tamagotchi + exercise jam!

### PR DESCRIPTION
**Pull request by ymfpfp**
**Note: This does not qualify for the bounty. As in, I don't want the $200 but the $200 should go to someone else.**

Thanks for making a PR! Please fill in the below:

Name: jc on Slack!

Do you run a club? Yep

What relevant experiences do you have to help you write this Jam? At Assemble ran a quick workshop on building a [Pokedex in React Native](https://www.jianminchen.com/article/general/2022-09-03-react-native-pokedex) and this is built on top of that. 

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam? On Slack 24/7/365. Joking obviously but yes.

### CODE REVIEW

**Review by sarthaktexas — APPROVED** [review]
I have no comments here.

**Review by Arpan-206 — APPROVED** [review]
Looks Brilliant to me!

**Review by faisalsayed10 — APPROVED** [review]
This is fun!

**Comment by SerenityUX** [comment]
biggest challenge will be customization opportunity, but this seems like a lot of fun! :D

**Pull request merged**
