### PR TITLE
Creating interactive 3D worlds on the web

### PR DESCRIPTION
**Pull request by linkai101**
I know there's a jam already approved for three.js with voxels but this one involves designing the 3D models with Spline along with implementing them on a website.

Also, I formatted this one for 2 parts: one 1-hour jam for Spline and one 1-hr jam for implementing it with three.js, so that there's enough time for playing around and designing. Let me know your thoughts on this and whether or not it should be one continuous jam.

Name: Linkai Wu

Do you run a club?
I started one at Blair HS! (just graduated)

What relevant experiences do you have to help you write this Jam?
Though I've relatively new to Spline and designing 3D models, I've been doing web development for all of HS! My [current website](https://linkaiwu.com) has a good example of what stuff learned in this Jam could be used for. :)

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam?
Yup!

### CODE REVIEW

**Comment by SerenityUX** [comment]
wowwwww, this is awesome! I wonder if there is room for allowing Jammers to work together in clubs using the Spline colab feature. Maybe Jammers could make their own interactive world by combining the works they make! :D

LOVVEEEE THISSSS

**Review by miguelaenlle — APPROVED** [review]
Looks great Linkai! Having 2 workshops should be okay, since assets are provided for people who didn't attend the first one, and a different technology is covered than in the last meetup. Making them one workshop would be too much for a 1-hour meetup.

**Review by Arpan-206 — APPROVED** [review]
Looking forward to seeing this coming to life!

**Review by zeyuyaoy — APPROVED** [review]
Woahhhhh, 3D stuff - same comments as @SerenityUX; it would be sooo cool if we could combine the works and build a tool for club leaders to merge all the works that their members created into a gallery or a "world" 🚀

**Pull request merged**
