### PR TITLE
PCB Business Card Jam Proposal

### PR DESCRIPTION
**Pull request by maggie-j-liu**
Thanks for making a PR! Please fill in the below:

Name: Maggie Liu

Do you run a club? 
I did (just graduated :p)

What relevant experiences do you have to help you write this Jam?
I've done this project and also previously hosted a workshop call on the same topic!

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam?
Yes

### CODE REVIEW

**Comment by sarthaktexas** [comment]
This is not a web-based jam, so therefore won't be accepted this round, but we love this project, and look forward to reviewing this later this year.

**Comment by maggie-j-liu** [comment]
hii @sarthaktexas! i asked abt this in #jams and belle said it would be ok! https://hackclub.slack.com/archives/C058T2CJUNR/p1687554466067229

unless by "not web-based" you mean can't be done on a chromebook -- easyeda is an online editor, so no download is required

**Comment by sarthaktexas** [comment]
Ah, my bad. Thanks for telling me, it was probably a miscommunication.

**Review by sarthaktexas — APPROVED** [review]
This looks great. Thanks!

**Comment by SerenityUX** [comment]
"Hacker Card"?  (or something more catchy)

**Review by Arpan-206 — APPROVED** [review]
Looks fantastic!

Looking forward to seeing this as a Jam!

**Review by linkai101 — APPROVED** [review]
I rlly wish I ran something like this in my club. 😤 This is such a cool idea and I got nothing else to say.

**Pull request merged**
