### PR TITLE
Add a Zig Kernel jam!

### PR DESCRIPTION
**Pull request by knvi**
Thanks for making a PR! Please fill in the below:

Name: Wojciech

Do you run a club? Nope

What relevant experiences do you have to help you write this Jam? I have written a few kernels already, and I have solid understanding of low-level programming, since I've spent most of my programming time with it.

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam? Of course!

(pretty sure this jam would fit in an hour; the code I prepared beforehand is ~120 loc long. the reason I chose Zig is because it makes it really easy to create a simple kernel, in order to understand the base logic happening behind the boot, and also it allowed me to fit the code into a single file + a linker file (otherwise you would need to make an asm file if you'd not use a bootloader))

### CODE REVIEW

**Comment by knvi** [comment]
^ the ~120 loc version is only supported on Linux, otherwise I would need to prepare a build.zig file which would manage all the kernel-image-packing magic happening.

**Comment by Arpan-206** [comment]
We're only looking for PRs that can be done on the web (targeting Chromebooks) otherwise this PR looks super duper cool.

(I love making OSs and Kernels hehe)

**Comment by knvi** [comment]
got it. thanks for reviewing it though!

**Comment by Arpan-206** [comment]
I would love to see it as a Jam though, also any chance you could use an online platform for this?

**Comment by knvi** [comment]
I could experiment with this; if you could add me on discord - @knvi , I would give you updates without the need of consulting via PR comments haha

**Comment by knvi** [comment]
^ I tried using Replit free plan, but it is not powerful enough

**Comment by Arpan-206** [comment]
Do you still want to work on this, I don't think it'll qualify for the bounty tho.

@SerenityUX we still accept non web jams right even if not for bounty?

**Comment by sarthaktexas** [comment]
because this isn't web based, we won't accept this proposal for the bounty. i'm sorry!

**Pull request closed without merging**
