### PR TITLE
 3D Platformer Game With Godot

### PR DESCRIPTION
**Pull request by euphoric3hub**
Thanks for making a PR! Please fill in the below:

Name: Euphoric3hub

Do you run a club? na

What relevant experiences do you have to help you write this Jam? I am currently making a game with godot

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam?
All time

### CODE REVIEW

**Comment by euphoric3hub** [comment]
This is the same as previous pr and i feel this is more feasible , so I would like to continue the same

**Review by linkai101 — CHANGES_REQUESTED** [review]
I'm a bit confused since this looks word for word exactly like the merged proposal by JackTDC. (https://github.com/hackclub/jams/pull/13)

Also, looks like you created a new folder called "jam" and deleted the example file -- please keep example.md and add your proposal file in the "jams" folder instead.

**Comment by euphoric3hub** [comment]
> I'm a bit confused since this looks word for word exactly like the merged proposal by JackTDC. (#13)
> 
> Also, looks like you created a new folder called "jam" and deleted the example file -- please keep example.md and add your proposal file in the "jams" folder instead.

hey JackTDC is not working on this jam, so Thomas asked me to take up on this project as I previously proposed the same jam unknowingly and later deleted it

**Comment by linkai101** [comment]
> > I'm a bit confused since this looks word for word exactly like the merged proposal by JackTDC. (#13)
> > Also, looks like you created a new folder called "jam" and deleted the example file -- please keep example.md and add your proposal file in the "jams" folder instead.
> 
> hey JackTDC is not working on this jam, so Thomas asked me to take up on this project as I previously proposed the same jam unknowingly and later deleted it

Ah if that's the case then no problem. 👍

**Pull request merged**
